### ISSUE TITLE
The patch is having issues with today update (May 10 update)

### ISSUE THREAD

**Issue by Hupmin** [ImaterialC/PriconneRe-TL#47]
The patch doesn't load until it is updated again.

**Comment by tynave** [comment]
The patch will break on every bigger game update now, and will need some files to be updated. Please wait patiently for it.

**Comment by Hupmin** [comment]
Yes. Luckily, we don't have to remove the update to make the game load. Only the patch isn't loaded.

**Comment by Hupmin** [comment]
Yes. Luckily we don't have to remove the update to make the game load. Only the patch isn't loaded

**Comment by Hupmin** [comment]
The problem is fixed
