### ISSUE TITLE
Error trade in new champion

### ISSUE THREAD

**Issue by jesuispt** [ImaterialC/PriconneRe-TL#49]
### **_Hello,_**
_Hello, I'd like to let you know about a translation that wasn't done with the new update for the new character, it's rather annoying to read the skills and that sort of thing! Thank you for taking my problem into account and thank you for the translation, which saves me a lot of time when it comes to understanding the game._
![image_2024-08-15_180927007](https://github.com/user-attachments/assets/042b31fa-0dae-461e-94a9-84d49ece29c3)

**Comment by ImaterialC** [comment]
look like it is already resolved. 
you can issue it for fast respond at our disocrd
